cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

getintouch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import contactView, successView

urlpatterns = [
    url(r'^contact/$', contactView, name='contact'),
    url(r'^success/$', successView, name='success'),
]

websites_design_spot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from account import urls as urls_account
from webdes import urls as urls_webdes
from cart import urls as urls_cart
from search import urls as urls_search
from checkout import urls as urls_checkout
from getintouch import urls as urls_getintouch
from webdes.views import all_webdes
from webdes.views import webdes_home
from django.views import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', all_webdes, name='index'),
    url(r'^$', webdes_home, name='index'),
    url(r'^account/', include(urls_account)),
    url(r'^webdes/', include(urls_webdes)),
    url(r'^cart/', include(urls_cart)),
    url(r'^checkout/', include(urls_checkout)),
    url(r'^search/', include(urls_search)),
    url(r'^getintouch/', include(urls_getintouch)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT})
]

getintouch/models.py
from django.db import models

# Create your models here.

getintouch/forms.py
from django import forms

class GetInTouchForm(forms.Form):
    contact_name = forms.CharField(required=True, label="First Name")
    contact_surname= forms.CharField(required=False, label="Last Name")
    from_email = forms.EmailField(required=True, label="Email")
    contact_website = forms.CharField(required=False, label="Website")
    contact_company = forms.CharField(required=False, label="Company")
    message = forms.CharField(widget=forms.Textarea, required=True, label="Message")

getintouch/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import GetInTouchForm
from django.contrib import messages
from django.core.urlresolvers import reverse

def contactView(request):
    if request.method == 'GET':
        form = GetInTouchForm()
    else:
        form = GetInTouchForm(request.POST)
        if form.is_valid():
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            contact_name = form.cleaned_data['contact_name']
            try:
                send_mail(message, from_email, contact_name, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, "Your message has been sent successfully!")    
            return redirect('success')
            
    return render(request, "contact.html", {'form': form})

def successView(request):
    # return HttpResponse('Success! Thank you for your message.')
    return render(request, "success.html")

getintouch/templates/contact.html
<!-- TBD: success page message sent -->
{% extends 'base.html' %}
{% block page_title %}Contact - Webdes Design Spot{% endblock %}
{% block content %}

<!-- header -->
  <div class="position-relative overflow-hidden p-5 text-center header-bg">
    <div class="col-sm-12 col-md-12 p-5 mx-auto">
      <h1 class="display-4 font-weight-normal header-title">Websites Design Spot</h1>
    </div>
  </div>
<!-- end header -->
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-12">
      <div class="card border-top-0">
        <header class="card-header">
           <p class="text text-center">WDS make it easy for you to imagine and get a website that fulfills your wishes. 
             With designs and features for every kind of sites, 
            WDS will work with you from the template that you choose, Developing your site as you require, 
            and up to give Support every time you need it once the site is in production. Use the form below to get in touch. Our talented and friendly staff is ready 
            to take your ideas, questions or comments.</p>
        </header>
        <article class="card-body"> 
            <form role="form" action="" method="post" class="contact-form form-horizontal">
            {% csrf_token %}
            <div class="contact-details-container">
              <div class="row">
                <div class="col-md-4 col-lg-4">
                  <div class="form-group">
                    <label for="id_contact_name">First Name:</label> 
                    <input type="text" name="contact_name" required="" id="id_contact_name">
                  </div>
                  <div class="form-group">
                    <label for="id_contact_surname">Last Name:</label> 
                    <input type="text" name="contact_surname" id="id_contact_surname">
                  </div>
                  <div class="form-group">
                    <label for="id_from_email">Email:</label> 
                    <input type="email" name="from_email" required="" id="id_from_email">
                  </div>
                  <div class="form-group">
                    <label for="id_contact_website">Website:</label> 
                    <input type="text" name="contact_website" id="id_contact_website"> 
                  </div>
                  <div class="form-group">
                    <label for="id_contact_company">Company:</label> 
                    <input type="text" name="contact_company" id="id_contact_company">
                  </div>
                </div>
                <div class="col-md-8 col-lg-6">
                  <div class="form-group">
                    <label for="id_message">Message:</label> 
                    <textarea class= "form-textarea-contact" name="message" style="min-width: 100%" required="" id="id_message"></textarea>
                  </div>
                  <div class="form-group">
                      <button class="form-submit-contact" type="submit">Submit</button>
                  </div>
                </div>
                <div class="col-md-12 col-lg-2">
                  <div>
                    <h2 class="title"><u>Get in touch with us</u></h2>
                      <p class="text-contact">Our office hours are Monday through Friday, 9am to 5pm, 
                      and we attempt to respond any query within 1 business day.</p>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </article>
      </div>
    </div>
  </div>
{% endblock %}

getintouch/templates/success.html
{% extends 'base-without-navbar.html' %}
{% block page_title %}Success - Webdes Design Spot{% endblock %}
{% block content %}
<!-- header -->
  <div class="position-relative overflow-hidden p-5 text-center header-bg">
    <div class="col-sm-12 col-md-12 p-5 mx-auto">
      <div class="text-center">Thank you for your message! We'll contact to you soon!</div>
    </div>
    <div class="col-sm-12 col-md-12 p-5 mx-auto">
      <h1 class="display-4 font-weight-normal header-title">Websites Design Spot</h1>
    </div>
    <div class="col-sm-12 col-md-12 p-5">
      <a class="logo-company" href="/"><img src="/media/images/new_moon.png" width="200" height="200" alt="logo-websites-design-spot"></a>
    </div>
  </div>
<!-- end header -->
{% endblock %}