cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

webdes/urls.py
from django.conf.urls import url, include
from .views import all_webdes, WebdesDetail, filter_webdes
from .views import webdes_home

urlpatterns = [
    url(r'^$', all_webdes, name='webdes'),
    url(r'^(?P<pk>\d+)/$', WebdesDetail.as_view(), name='webdes-detail'),
    url(r'^$',  webdes_home, name='index'),
    url(r'^(?P<requestedCategory>[a-zA-Z ]*)$', filter_webdes, name='filter_webdes'),
]

websites_design_spot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from account import urls as urls_account
from webdes import urls as urls_webdes
from cart import urls as urls_cart
from search import urls as urls_search
from checkout import urls as urls_checkout
from getintouch import urls as urls_getintouch
from webdes.views import all_webdes
from webdes.views import webdes_home
from django.views import static
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', all_webdes, name='index'),
    url(r'^$', webdes_home, name='index'),
    url(r'^account/', include(urls_account)),
    url(r'^webdes/', include(urls_webdes)),
    url(r'^cart/', include(urls_cart)),
    url(r'^checkout/', include(urls_checkout)),
    url(r'^search/', include(urls_search)),
    url(r'^getintouch/', include(urls_getintouch)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT})
]

webdes/models.py
from django.db import models

# Create your models here

# It will create the database for the 'webdes'

class Webdes(models.Model):
    # It will add 'category' field to the db
    CATEGORY_CHOICES = [
        ('P', 'Professional'),
        ('E', 'Event'),
        ('A', 'Abastract'),
        ('EC', 'Ecommerce'),
        ('NP', 'Non-Profit'),
    ]

    name = models.CharField(max_length=254, default='')
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='images')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=20, default='Event')
   
    def __str__(self):
        return self.name

webdes/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import Webdes
from django.views.generic import DetailView

# all webdes view
def all_webdes(request):
    """Return all webdes in the DB and display webdes page"""

    webdes = Webdes.objects.all()
    paginator = Paginator(webdes, 8)  # show 8 webdes each page

    page = request.GET.get('page')
    try:
        webdes = paginator.page(page)
    except PageNotAnInteger:
        # retrieve first page
        webdes = paginator.page(1)
    except EmptyPage:
        # retrieve last page
        webdes = paginator.page(paginator.num_pages)

    return render(request, 'webdes.html', {'webdes': webdes})

# category view
def filter_webdes(request, requestedCategory):
    webdes = Webdes.objects.filter(category=requestedCategory)
    paginator = Paginator(webdes, 8)  # show 8 webdes

    page = request.GET.get('page')
    try:
        webdes = paginator.page(page)
    except PageNotAnInteger:
         # retrieve first page
        webdes = paginator.page(1)
    except EmptyPage:
         # retrieve last page
        webdes = paginator.page(paginator.num_pages)
    return render(request, 'webdes.html', {'webdes': webdes})

# home page view
def webdes_home(request):
    """Return header and all webdes in the DB and display home page"""

    webdes = Webdes.objects.all()
    return render(request, 'index.html', {'webdes': webdes})


# Information about a specific webdes

class WebdesDetail (DetailView):
    model = Webdes

templates/webdes/webdes_detail.html
{% extends 'base.html' %}
{% block page_title %}{{ webdes.name }}{% endblock %}
{% block page_heading %}{{ webdes.name }}{% endblock %}
{% block content %}
<div class="webdes-detail-container">
    <div class="webdes panel-body">
        <div class="row row-flex flex-column-reverse flex-md-row p-2 p-md-3 p-lg-5 m-0">
            <div class="col-xs-10 col-xs-offset-1 col-sm-offset-0 col-sm-6 col-md-6 display panel panel-default">
                <h2 class="webdes-detail-title pt-2">{{ webdes.name }}</h2>
                {% for category in webdes.categorys.all %}
                <a href="{% url 'webdes_category' category.name %}">
                    {{ category.name }}
                </a>
                {% endfor %}
                <hr>
                <p class="webdes-description pb-xl-5">{{ webdes.description }}</p>
                 {% if user.is_authenticated %}
                <div class="webdes-details">
                    <p class="webdes-price mb-0">{{ webdes.price }}&nbsp;&euro; </span class="webdes-category">Category: {{ webdes.get_category_display }}</span></p>
                    <form class="webdes-detail-qty-form" method="post" action="{% url 'add_to_cart' webdes.id %}">
                        {% csrf_token %}
                        <div class="input-group webdes-quantity">
                            <input name="quantity" type="number" min="1" max="999" value="0" class="form-control qty-input">
                            <span class="input-group-btn">
                                <button class="btn btn-webdes-detail" type="submit">Add</button>
                            </span>
                        </div>
                    </form>
                </div>
                {% endif %}
            </div>
            <div class="col-xs-10 col-xs-offset-1 col-sm-offset-0 col-sm-6 col-md-6 display panel panel-default pt-2">
                <div class="webdes-detail-image webdes-image frame" style="background-image: url('{{ MEDIA_URL }}{{ webdes.image }}')"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}